blank_issues_enabled: true

contact_links:
  - name: Cog Support Discord Server
    url: https://discord.gg/GET4DVk
    about: For help with my cogs or to report bugs/errors, you can also go to my support channel in the server.
